const freezeFish = (fish) => Object.freeze({ ...fish })

export const OFFICIAL_FISH_PROFILE = Object.freeze({
  frameInterval: 1000 / 30,
  maxPixelRatio: 1.5,
  minWidth: 768,
  resizeDelay: 150,
  boundaryPadding: 12,
  boundaryLookAhead: 72,
  boundaryWeight: 2.8,
  mouseAvoidRadius: 150,
  mouseAvoidWeight: 2.4,
  separationRadius: 90,
  separationWeight: 1.5,
  maxTurnRate: 1.9,
  wanderAngle: Math.PI * 0.9,
  wanderMinSeconds: 1.4,
  wanderMaxSeconds: 3.4,
  tailFrequency: 2.2,
  fluidRadius: 0.065,
  fluidStrength: 0.55,
  fish: Object.freeze([
    freezeFish({
      id: 'fish-a',
      length: 44,
      speed: 34,
      color: '#8fc7ff',
      accentColor: '#e7f6ff',
      detailColor: '#173754',
      opacity: 0.72,
      initialX: 0.28,
      initialY: 0.34,
      initialHeading: 0.2,
    }),
    freezeFish({
      id: 'fish-b',
      length: 38,
      speed: 42,
      color: '#fff0c2',
      accentColor: '#fffbea',
      detailColor: '#594c2e',
      opacity: 0.66,
      initialX: 0.72,
      initialY: 0.62,
      initialHeading: Math.PI + 0.25,
    }),
  ]),
})
